import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"
import { Menu } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en" className="">
        <body className="flex min-h-screen">
            <div className="hidden md:flex w-52 border-r border-gray-200 min-h-screen ">
                    <Sidebar/>
            </div>        
            <div className="flex flex-1 flex-col h-full">
                <Header/>
                {children}        
            </div>  
            <Toaster richColors />
        </body>
        </html>
    </ClerkProvider>
  );
}
