import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body className="flex flex-col min-h-screen">
            <Header/>
            <div className="flex flex-1 bg-green-400">
                <Sidebar/>
                {children}
            </div>
            <Toaster richColors />
        </body>
        </html>
    </ClerkProvider>
  );
}
